example/Smartflow.Web.Mvc/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Smartflow.BussinessService.WorkflowService;
using Smartflow.BussinessService.Services;
using Smartflow.BussinessService.Models;

namespace Smartflow.Web.Controllers
{
    public class DefaultController : Controller
    {
        private IWorkflowDesignService workflowStructureService=WorkflowServiceProvider.OfType<IWorkflowDesignService>();

        public ActionResult Main()
        {
            User userInfo = System.Web.HttpContext.Current.Session["user"] as User;
            ViewBag.EmployeeName = userInfo.EMPLOYEENAME;
            return View();
        }

        public ActionResult List()
        {
            return View(workflowStructureService.GetWorkflowStructureList());
        }

        public JsonResult Delete(string WFID)
        {
            workflowStructureService.Delete(WFID);
            return Json(true);
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Pending()
        {
            User userInfo = System.Web.HttpContext.Current.Session["user"] as User;
            return View(new PendingService().Query(userInfo.IDENTIFICATION));
        }

        public JsonResult GetPendingCount()
        {
            User userInfo = System.Web.HttpContext.Current.Session["user"] as User;
            if (userInfo == null)
            {
                return Json(0);
            }
            else
            {
                return Json(new PendingService().Query(userInfo.IDENTIFICATION).Count);
            }
        }


        public JsonResult GetUser(string userName)
        {
            //演示使用
            Smartflow.BussinessService.Models.User userInfo = new UserService().GetUser(userName);

            if (userInfo == null)
            {
                return Json(false);
            }
            else
            {
                System.Web.HttpContext.Current.Session["user"] = userInfo;
                return Json(true);
            }
        }
    }
}

example/Smartflow.Web.Mvc/Controllers/FileApplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Smartflow.BussinessService.Models;
using Smartflow.BussinessService.WorkflowService;
using Smartflow.BussinessService.Services;
using Smartflow.Web.Mvc.Code;

namespace Smartflow.Web.Controllers
{
    public class FileApplyController : Controller
    {
        private BaseWorkflowService bwfs = BaseWorkflowService.Instance;
        private ApplyService fileApplyService = new ApplyService();

        public ActionResult Save(Apply model)
        {
            model.STATUS = 0;
            fileApplyService.Persistent(model);
            return RedirectToAction("FileApplyList");
        }

        public ActionResult Submit(Apply model)
        {
            model.INSTANCEID = bwfs.Start(model.STRUCTUREID);
            model.STATUS = 1;
            fileApplyService.Persistent(model);
            return RedirectToAction("FileApplyList");
        }

        public ActionResult FileApplyList()
        {
            return View(fileApplyService.Query());
        }

        public void Delete(long id)
        {
            fileApplyService.Delete(id);
        }

        public ActionResult FileApply(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                GenerateSecretViewData(string.Empty);
                GenerateWFViewData(string.Empty);
                return View();
            }
            else
            {
                Apply mdl = fileApplyService.GetInstance(long.Parse(id));
                GenerateSecretViewData(mdl.SECRETGRADE);
                GenerateWFViewData(mdl.STRUCTUREID);

                if (mdl.STATUS == 1)
                {
                    var executeNode = bwfs.GetCurrentPrevNode(mdl.INSTANCEID);
                    var current = bwfs.GetCurrent(mdl.INSTANCEID);

                    ViewBag.ButtonName = current.APPELLATION;
                    ViewBag.PreviousButtonName = executeNode == null ? String.Empty : executeNode.APPELLATION;
                    ViewBag.UndoCheck = CommonMethods.CheckUndoButton(mdl.INSTANCEID);
                    ViewBag.UndoAuth = executeNode == null ? true : CommonMethods.CheckUndoAuth(mdl.INSTANCEID);
                    ViewBag.JumpAuth = current.APPELLATION == "开始" ? true : CommonMethods.CheckAuth(current.NID, mdl.INSTANCEID);
                    ViewBag.UserList= new UserService().GetPendingUserList(current.NID, mdl.INSTANCEID);
                }
                return View(mdl);
            }
        }

        public void GenerateWFViewData(string WFID)
        {
            List<WorkflowStructure> workflowXmlList = WorkflowServiceProvider
                .OfType<IWorkflowDesignService>()
                .GetWorkflowStructureList();
            
            
            List<SelectListItem> fileList = new List<SelectListItem>();
            foreach (WorkflowStructure item in workflowXmlList)
            {
                fileList.Add(new SelectListItem { Text = item.APPELLATION, Value = item.IDENTIFICATION, Selected = (item.IDENTIFICATION == WFID) });
            }
            ViewData["WFiles"] = fileList;
        }

        public void GenerateSecretViewData(string secretGrade)
        {
            List<string> secrets = new List<string>() { 
              "非密",
              "秘密",
              "机密",
              "绝密"
            };
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (string secret in secrets)
            {
                list.Add(new SelectListItem { Text = secret, Value = secret, Selected = (secret == secretGrade) });
            }
            ViewData["SECRET"] = list;
        }
    }
}

example/Smartflow.Web.Mvc/Controllers/UserController.cs
using Smartflow.BussinessService.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Smartflow.Web.Mvc.Controllers
{
    public class UserController : Controller
    {
        private UserService userService = new UserService();

        //
        // GET: /User/
        public ActionResult UserList()
        {
            return View(userService.GetUserList());
        }

        //
        // GET: /User/
        public ActionResult RoleStatistics()
        {
            return View(userService.GetStatisticsDataTable());
        }
    }
}

example/Smartflow.Web.Mvc/Views/Shared/List.cshtml
@model System.Collections.Generic.IEnumerable<Smartflow.WorkflowStructure>
@using Smartflow
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Smartflow-Sharp 工作流程列表</title>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <style type="text/css">
        .layui-btn {border-radius: initial;}
    </style>
    <script src="~/Content/jquery.min.js"></script>
    <script src="~/Content/common.js"></script>
    <script type="text/javascript">
        function delWf(id) {
            if (window.confirm('删除？')) {
                $.ajax({
                    url: '@Url.Action("Delete", "Default")',
                    type: 'post',
                    data: { WFID: id },
                    success: function () {
                        document.location.href = '@Url.Action("List", "Default")';
                    }
                });
            }
        }
    </script>
</head>
<body>
    <br />
    <div class="layui-container">
        <div class="layui-btn-group">
            <input type="button" value="增加" class="layui-btn  layui-btn-sm" onclick="openWin('../../Smartflow.Web.Design/WorkflowDesign/Design', 960, 560)" />
        </div>
        <table class="layui-table">
            <thead>
                <tr>
                    <th>名称</th>
                    <th style="width:120px;text-align:center;">操作</th>
                </tr>
            </thead>
            <tbody>
                @foreach (WorkflowStructure wf in Model)
                {
                    <tr>
                        <td>@wf.APPELLATION</td>
                        <td style="width:120px;text-align:center;">
                            <a class="layui-btn layui-btn-xs" href="javascript:openWin('../../Smartflow.Web.Design/WorkflowDesign/Design?id=@wf.IDENTIFICATION',960,560)">修改</a>
                            <a class="layui-btn layui-btn-danger layui-btn-xs" href="javascript:delWf('@wf.IDENTIFICATION')">删除</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

example/Smartflow.Web.Mvc/Views/Shared/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Smartflow-Sharp工作流管理平台</title>
    <link href="~/Content/login.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>

    <script type="text/javascript">

        $(function () {

            //用于演示
            $("#btnLogin").click(function () {
                var userName = document.getElementById("userName").value;
                if ($.trim(userName)) {
                    $.ajax({
                        url: '@Url.Action("GetUser","Default")',
                        data: { userName: userName },
                        dataType: 'json',
                        type: 'post',
                        cache: false,
                        success: function (result) {
                            if (result) {
                                window.location.href = '@Url.Action("Main","Default")';
                            } else {
                                alert('登录失败');
                            }
                        }
                    });
                }
            });
        });

    </script>
</head>
<body>
    <div class="login">
        <div class="message">Smartflow-Sharp工作流管理平台</div>
        <div id="darkbannerwrap"></div>
        <form method="post">
            <input name="action" value="login" type="hidden" />
            <input name="username" placeholder="用户名" type="text" value="chengderen" id="userName" />
            <hr class="hr15">
            <input name="password" placeholder="密码可不填" type="password" />
            <hr class="hr15">
            <input value="登录" style="width:100%;" type="button" id="btnLogin" />
            <hr class="hr20">
        </form>
    </div>
</body>
</html>

example/Smartflow.Web.Mvc/Views/Shared/Main.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Smartflow-Sharp工作流管理平台</title>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>
    <script src="~/Content/layui/layui.all.js"></script>

    <style>
        .top-menu-container {
            margin-right: 40px;
        }

        .top-menu {
            float: right;
        }

        .top-menu-item {
            height: 65px;
            width: 70px;
            display: inline-block;
            padding-top: 48px;
            cursor: pointer;
            text-align: center;
        }

            .top-menu-item span {
                color: #fff;
                font-weight: 300;
                font-size: 13px;
            }
    </style>
    <script type="text/javascript">
        $(function () {
            $("#off").click(function () {
                //具体逻辑就不写，仅为演示使用
                window.location.href = '@Url.Action("Login", "Default")';
            });
        });

        $(function () {

            //仅演示:轮询查询待办数量
            setInterval(function () {
                $.ajax({
                    url: '@Url.Action("GetPendingCount", "Default")',
                    type: 'post',
                    success: function (data) {
                        $("#items").text(data);
                    }
                });
            }, 1000 * 5);

            $("#message").click(function () {
                //iframe窗
                layer.open({
                    type: 2,
                    title: "待办",
                    closeBtn: 1, //不显示关闭按钮
                    shade: 0,
                    //shadeClose: true,
                    area: ['400px', '400px'],
                    offset: 'rb', //右下角弹出
                    //time: 2000, //2秒后自动关闭
                    anim: 2,
                    content: ['@Url.Action("Pending","Default")', 'no'] //iframe的url，no代表不显示滚动条
                });
            });
        });
    </script>
</head>
<body class="mainFrame">
    <div class="top">
        <span class="top-header">Smartflow-Sharp 工作流管理平台</span>
        <div class="top-menu-container">
            <div class="top-menu">
                <div class="top-menu-item" style="background:  url(../Content/images/user.png) no-repeat center center;">
                    <span>@(ViewBag.EmployeeName)</span>
                </div>
                <div class="top-menu-item" style="background:  url(../Content/images/message.png) no-repeat center center;" id="message">
                    <span>消息(<i style="color:red;padding-right:2px;" id="items">0</i>)</span>
                </div>
                <div class="top-menu-item" style="background:  url(../Content/images/off.png) no-repeat center center;" id="off">
                    <span>注销</span>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="left menu">
            <div class="menu-item">
                <ul class="menu-sub-items">
                    <li>
                        <a href="@Url.Action("FileApplyList", "FileApply")" target="frmContent">文件定密申请</a>
                    </li>
                    <li>
                        <a href="@Url.Action("UserList", "User")" target="frmContent">用户信息</a>
                    </li>
                    <li>
                        <a href="@Url.Action("RoleStatistics", "User")" target="frmContent">按角色统计</a>
                    </li>
                    <li>
                        <a href="@Url.Action("List", "Default")" target="frmContent">流程设计器</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="right">
            <iframe style="width:100%;height:100%;"
                    id="frmContent"
                    name="frmContent"
                    frameborder="0"
                    src="@Url.Action("FileApplyList", "FileApply")"></iframe>
        </div>
    </div>
</body>
</html>

example/Smartflow.Web.Mvc/Views/Shared/Pending.cshtml
@{
    Layout = null;
}
@model System.Collections.Generic.IEnumerable<Smartflow.BussinessService.Models.Pending>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>待办事项</title>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>

    <style type="text/css">
        .layui-table a {
            color: red;
        }
    </style>
</head>
<body>
    <br />
    <div class="layui-container">

        <table class="layui-table">
            <thead>
                <tr>
                    <th>待办任务列表</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Smartflow.BussinessService.Models.Pending wf in Model)
                {
                    <tr>
                        <td>@Html.Raw(wf.APPELLATION)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <script src="~/Content/layui/layui.js"></script>
</body>
</html>

example/Smartflow.Web.Mvc/Views/Shared/RoleStatistics.cshtml
@model System.Data.DataTable
@using System.Data
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Smartflow-Sharp 工作流程列表</title>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <style type="text/css">
        .layui-btn {
            border-radius: initial;
        }
    </style>
    <script src="~/Content/jquery.min.js"></script>
</head>
<body>
    <br />
    <div class="layui-container">
        <table class="layui-table">
            <thead>
                <tr>
                    <th>用户名</th>
                    <th>姓名</th>
                    <th>角色名称</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in Model.Rows)
                {
                    <tr>
                        <td>@row["USERNAME"]</td>
                        <td>@row["EMPLOYEENAME"]</td>
                        <td>@row["APPELLATION"]</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

example/Smartflow.Web.Mvc/Views/Shared/UserList.cshtml
@model System.Collections.Generic.IEnumerable<Smartflow.BussinessService.Models.User>
@using Smartflow.BussinessService.Models
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Smartflow-Sharp 工作流程列表</title>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <style type="text/css">
        .layui-btn {
            border-radius: initial;
        }
    </style>
    <script src="~/Content/jquery.min.js"></script>
</head>
<body>
    <br />
    <div class="layui-container">
        <table class="layui-table">
            <thead>
                <tr>
                    <th>用户名</th>
                    <th>姓名</th>
                </tr>
            </thead>
            <tbody>
                @foreach (User mdl in Model)
                {
                    <tr>
                        <td>@mdl.USERNAME</td>
                        <td>@mdl.EMPLOYEENAME</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>