src/Smartflow.Web.Design/Controllers/BaseController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Smartflow.Web.Design.Controllers
{
    public class BaseController : Controller
    {
        public JsonResult JsonWrapper(Object data)
        {
            return new JsonResultWrapper()
            {
                Data = data,
                ContentType = "application/json"
            };
        }
    }

    public class JsonResultWrapper : JsonResult
    {
        public JsonResultWrapper()
            : base()
        {

        }

        public override void ExecuteResult(ControllerContext context)
        {
            HttpResponseBase response = context.HttpContext.Response;
            string data = Newtonsoft.Json.JsonConvert.SerializeObject(this.Data,
                new Newtonsoft.Json.JsonSerializerSettings()
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                    //ContractResolver=new DefaultContractResolver()
                    ContractResolver = new UpperCaseContractResolver()

                });
            response.Write(data);
        }

        public class UpperCaseContractResolver : Newtonsoft.Json.Serialization.DefaultContractResolver
        {
            protected override string ResolvePropertyName(string propertyName)
            {
                return propertyName.ToUpper();
            }
        }
    }
}

src/Smartflow.Web.Design/Controllers/WorkflowDesignController.cs
/********************************************************************
 License: https://github.com/chengderen/Smartflow/blob/master/LICENSE 
 Home page: https://www.smartflow-sharp.com
 ********************************************************************
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Web.Script.Serialization;
using Smartflow;
using System.Data;

namespace Smartflow.Web.Design.Controllers
{
    public partial class WorkflowDesignController : BaseController
    {
        private IWorkflowDesignService designService = WorkflowServiceProvider.OfType<IWorkflowDesignService>();
        private ActorService roleService = new ActorService();

        public ActionResult Design(string id)
        {
            ViewBag.WFID = id;
            return View();
        }

        public JsonResult GetWorkflowStructure(string WFID)
        {
            WorkflowStructure model = designService.GetWorkflowStructure(WFID);
            return Json(model);
        }

        public JsonResult Save(WorkflowStructure model)
        {
            if (String.IsNullOrEmpty(model.IDENTIFICATION))
            {
                model.IDENTIFICATION = Guid.NewGuid().ToString();
                model.FILESTRUCTURE = HttpUtility.UrlDecode(model.FILESTRUCTURE);
                designService.Persistent(model);
            }
            else
            {
                model.FILESTRUCTURE = HttpUtility.UrlDecode(model.FILESTRUCTURE);
                designService.Update(model);
            }
            return Json(true);
        }

        public ActionResult WorkflowImage(string instanceID)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            ViewBag.Result = serializer.Serialize(WorkflowInstance.GetInstance(instanceID));

            DataTable dt = WorkflowServiceProvider.OfType<IWorkflowActor>().GetRecord(instanceID);
            ViewBag.Record = Newtonsoft.Json.JsonConvert.SerializeObject(dt);

            return View();
        }

        public ActionResult WorkflowDesignSettings()
        {
            return View();
        }

        public JsonResult GetRole(string roleIds, string searchKey)
        {
            return JsonWrapper(roleService.GetRole(roleIds, searchKey));
        }

        public JsonResult GetConfigs()
        {
            return JsonWrapper(WorkflowServiceProvider
                .OfType<IWorkflowConfiguration>()
                .GetWorkflowConfigs());
        }
    }
}

src/Smartflow.Web.Design/Views/WorkflowDesign/Design.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <title>Smartflow-Sharp工作流程设计器</title>
    <link href="~/Content/smartflow.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>
    <script src="~/Content/svg.js"></script>
    <script src="~/Content/layui/layui.all.js"></script>

    <script src="~/Content/smartflow.js"></script>
    <script src="~/Content/design.js"></script>
    <script type="text/javascript">
        $(function () {
            design.init({
                id: '@ViewBag.WFID',
                container: 'drawing',
                windowUrl: '@Url.Action("WorkflowDesignSettings", "WorkflowDesign")',
                instanceUrl: '@Url.Action("GetWorkflowStructure", "WorkflowDesign")',
                saveUrl: '@Url.Action("Save", "WorkflowDesign")'
            });

            $(".tools-menu img").mousedown(function () {
                $(this).css("border", "solid 1px #ad9d9d");
            });
            $(".tools-menu img").mouseup(function () {
                $(this).css("border", "none");
            });
        });

    </script>
</head>
<body>
    <div class="tools">
        <ul class="tools-menu">
            <li>
                <img src="~/Content/images/save.png" onclick="design.save()"
                     title="保存" />
            </li>
            <li>
                <img src="~/Content/images/select.png" onclick="SMF.select()"
                     title="选择" />
            </li>
            <li>
                <img src="~/Content/images/line.png" onclick="SMF.connect()"
                     title="连接" />
            </li>
            <li>
                <img src="~/Content/images/node.png" onclick="SMF.create('node')"
                     title="节点" />
            </li>
            <li>
                <img src="~/Content/images/decision.png" onclick="SMF.create('decision')"
                     title="决策" />
            </li>
            <li>
                <img src="~/Content/images/left.png" onclick="SMF.alignment()"
                     title="左对齐" />
            </li>
            <li>
                <img src="~/Content/images/help.png" onclick="design.openWin('note')"
                     title="帮助" />
            </li>
        </ul>
    </div>
    <div class="container-ctr">
        <div class="container-draw" id="drawing"></div>
    </div>
    <script type="text/html" id="note">
        <table class="smartflow-table note-table">
            <tr>
                <td class="note-column">方向：</td>
                <td class="note-content">流程设计工具仅支持从上往下</td>
            </tr>
            <tr>
                <td class="note-column">规则：</td>
                <td class="note-content">开始节点至少有一条出线，但没有进线、结束节点至少有一条进线，但没有出线，普通节点至少有一进一出的连线，决策节点至少有一条进线，两条以上出线</td>
            </tr>
            <tr>
                <td class="note-column">连线：</td>
                <td class="note-content">先点击左边线条图标，然后选中节点，按下鼠标左键拖动到另一节点，然后再松手，两节点间会出现连接线</td>
            </tr>
            <tr>
                <td class="note-column">移动：</td>
                <td class="note-content">先点击左边鼠标箭头，然后选择节点元素，按下鼠标左键进行移动</td>
            </tr>
            <tr>
                <td class="note-column">编辑：</td>
                <td class="note-content">鼠标双击元素，然后弹出编辑页面</td>
            </tr>
            <tr>
                <td class="note-column">删除：</td>
                <td class="note-content">按住键盘中Ctrl+Alt键，然后鼠标双击元素，元素就会被删除</td>
            </tr>
        </table>
    </script>
</body>
</html>

src/Smartflow.Web.Design/Views/WorkflowDesign/List.cshtml
@model System.Collections.Generic.IEnumerable<Smartflow.Integration.Models.WorkflowXml>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Smartflow 工作流程列表</title>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>
    <script src="~/Content/common.js"></script>
    <script type="text/javascript">
        function delWf(id) {
            if (window.confirm('删除？')) {
                $.ajax({
                    url: '@Url.Action("Delete", "WorkflowDesign")',
                    type: 'post',
                    data: { WFID: id },
                    success: function () {
                        document.location.href = '@Url.Action("List", "WorkflowDesign")';
                    }
                });
            }
        }
    </script>
</head>
<body>
    <br />
    <div class="layui-container">
        <div class="layui-btn-group">
            <input type="button" value="增加" class="layui-btn" onclick="openWin('@Url.Action("Design", "WorkflowDesign")',960,560)" />
        </div>
        <table class="layui-table">
            <thead>
                <tr>
                    <th style="width:50px;">序号</th>
                    <th>名称</th>
                    <th style="width:120px;text-align:center;">操作</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                }
                @foreach (Smartflow.Integration.Models.WorkflowXml wf in Model)
                {
                    <tr>
                        <td style="width:50px;text-align:center;">@(counter++)</td>
                        <td>@wf.NAME</td>
                        <td style="width:120px;text-align:center;">
                            <a href="javascript:openWin('@Url.Action("Design", "WorkflowDesign", new { id = wf.WFID })',960,560)">修改</a>
                            <a href="javascript:delWf('@wf.WFID')">删除</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <script src="~/Content/layui/layui.js"></script>
</body>
</html>

src/Smartflow.Web.Design/Views/WorkflowDesign/WorkflowDesignSettings.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>流程节点数据配置</title>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <link href="~/Content/smartflow.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>
    <script src="~/Content/settings.js"></script>
    <script type="text/javascript">
        $(function () {
            SMF.init({
                configUrl: '@Url.Action("GetConfigs", "WorkflowDesign")',
                roleUrl: '@Url.Action("GetRole", "WorkflowDesign")'
            });

            $("#btnSearch").click(function () {
                var searchKey = $.trim($(".smartflow-search-input").val());
                SMF.search(searchKey || '');
            });
        });
    </script>
</head>
<body>
    <div class="layui-container">
        <div class="layui-tab layui-tab-brief">
            <ul class="layui-tab-title" id="tab">
                <li category="info" class="layui-this">基本信息</li>
                <li category="role">参与角色</li>
                <li category="rule">规则配置</li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show">
                    <table class="layui-table" lay-skin="nob">
                        <tr>
                            <td style="width:60px;" class="layui-text">名称</td>
                            <td>
                                <input type="text" id="txtNodeName" class="layui-input smartflow-input" />
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="layui-tab-item">
                    <div class="layui-row">
                        <div class="layui-col-xs6">
                            <div class="smartflow-role-box">
                                <div style="padding-bottom:5px;position:relative;">
                                    <input type="text" placeholder="按角色名称搜索" class="layui-input smartflow-input smartflow-search-input" />
                                    <span class="layui-icon layui-icon-search smartflow-search-icon" id="btnSearch"></span>
                                </div>
                                <div class="smartflow-role-list">
                                    <ul id="roleGrid" class="smartflow-list"></ul>
                                </div>
                            </div>
                        </div>
                        <div class="layui-col-xs6">
                            <fieldset class="layui-elem-field layui-elem-field-h" style="margin-left:10px;">
                                <legend>已选角色</legend>
                                <div class="layui-field-box">
                                    <ul id="roleAssign" class="smartflow-list"></ul>
                                </div>
                            </fieldset>
                        </div>
                    </div>
                </div>
                <div class="layui-tab-item">
                    <fieldset class="layui-elem-field layui-field-title layui-field-title-mp">
                        <legend>SQL脚本</legend>
                    </fieldset>
                    <table class="layui-table smartflow-table-tb" lay-skin="nob">
                        <tbody>
                            <tr>
                                <td style="width:120px;" class="layui-text">
                                    数据源
                                </td>
                                <td>
                                    <select id="ddlRuleConfig" class="layui-select smartflow-input" style="width:100%;"></select>
                                </td>
                            </tr>
                            <tr>
                                <td style="width:120px;" class="layui-text">SQL脚本</td>
                                <td>
                                    <input id="txtCommand" class="layui-input smartflow-input" spellcheck="false" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <fieldset class="layui-elem-field  layui-field-title layui-field-title-mp">
                        <legend>表达式配置</legend>
                    </fieldset>
                    <div style="height:200px;overflow: auto;">
                        <table class="layui-table smartflow-table-tb" id="transitions" lay-skin="nob">
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Content/layui/layui.js"></script>
    <script type="text/javascript">
        //注意：选项卡 依赖 element 模块，否则无法进行功能性操作
        layui.use(['element', 'form'], function () {
        });
    </script>
</body>
</html>

src/Smartflow.Web.Design/Views/WorkflowDesign/WorkflowImage.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta name="viewport" content="width=device-width" />
    <title>Smartflow 业务流程图</title>
    <link href="~/Content/smartflow.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>
    <script src="~/Content/json2.js"></script>
    <script src="~/Content/svg.js"></script>
    <script src="~/Content/smartflow.js"></script>
    <script type="text/javascript">
    $(function () {
        var draw = window.SMF.init({container:'drawing'}),
                serverData=@Html.Raw(ViewBag.Result),
                processData=@(ViewBag.Record==null?"''":Html.Raw(ViewBag.Record));
            if (serverData) {
                SMF.revert(serverData.STRUCTUREXML, true, serverData.Current.IDENTIFICATION,processData);
            }
        });
</script>
</head>
<body>
    <div class="container">
        <div class="container-draw" id="drawing"></div>
    </div>
</body>
</html>