Smartflow.Web/Controllers/UserCtlController.cs
using Smartflow.Web.Code;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Smartflow.Web.Controllers
{
    public class UserCtlController : Controller
    {
        private RecordService rservice = new RecordService();


        //
        // GET: /UserCtl/
        public PartialViewResult Record(string instanceID)
        {

            ViewBag.InstanceID = instanceID;

            return PartialView(rservice.Query(instanceID));
        }

        public ActionResult FlowImage(string instanceID)
        {
            ViewBag.WfID = instanceID;
            return View();
        }


        public JsonResult GetResult(string instanceID)
        {
            BaseWorkflowService bwkf = BaseWorkflowService.Instance;
            return Json(bwkf.GetInstance(instanceID));
        }

        //
        // GET: /UserCtl/
        public ActionResult FlowControl(string instanceID)
        {
            BaseWorkflowService bwkf = BaseWorkflowService.Instance;
            WorkflowInstance instance = bwkf.GetInstance(instanceID);

            ViewBag.InstanceID = instanceID;

            return View(instance.Current.Transitions);
        }


        public JsonResult Jump(string instanceID, string transitionID, long to, string message)
        {
            BaseWorkflowService bwkf = BaseWorkflowService.Instance;
            bwkf.Jump(instanceID, transitionID, to, data: new { Message = message });
            return Json(true);
        }
    }
}

Smartflow.Web/Views/Shared/FlowControl.cshtml
@model System.Collections.Generic.IEnumerable<Smartflow.Elements.Transition>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FlowControl</title>
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Content/jquery-1.6.4.min.js"></script>
    <style type="text/css">
        .flow-auditTable {
            margin: 0 auto;
            padding: 0;
            width: 98%;
        }

        .flow-head {
            width: 160px;
        }

        .flow-content {
        }
    </style>

    <script type="text/javascript">

        $(function () {

            $("#btnOk").click(function () {
                var transitions = $(".flow-content input[name='transition']:checked");
                if (transitions.length == 0) {
                    alert('请选择审批操作');
                } else {

                    var t = transitions[0];
                    var tid = $(t).attr("tid"),
                        to = $(t).attr("to");

                    var message = $("#txtDescription").val();

                    $.ajax({
                        url: '@Url.Action("Jump","UserCtl")',
                        type: 'post',
                        data: { instanceID: '@ViewBag.InstanceID', transitionID: tid, to: to,message:message },
                        success: function () {
                            window.close();
                        }
                    });
                }
            });
        });
    </script>

</head>
<body>
    <table class="flow-auditTable">
        <tr>
            <td class="flow-head">下一步审批操作：</td>
            <td class="flow-content">
                @foreach (var item in Model)
                {
                    <input id="rad@(item.ID)" tid="@item.ID" to="@item.TO" name="transition" type="radio" />
                    <label for="rad@(item.ID)">@item.NAME</label>
                }
            </td>
        </tr>
        <tr>
            <td class="flow-head">审批意见：</td>
            <td class="flow-content">
                <textarea rows="10" cols="25" style="width:95%;height:60px;" id="txtDescription"></textarea>
            </td>
        </tr>
        <tr>
            <td>
                <input type="button" id="btnOk" value="确定" />
            </td>
        </tr>
    </table>
</body>
</html>

Smartflow.Web/Views/Shared/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Smartflow 工作流程设计器</title>
    <link href="~/Content/smartflow.css" rel="stylesheet" />
    <script src="~/Content/jquery-1.6.4.min.js"></script>
    <script src="~/Content/svg.js"></script>
    <script src="~/Content/smartflow.js"></script>
    <script type="text/javascript">
        function saveflow() {
            var exportObj = SMF.exportToJSON();
            var flowName=window.prompt("请输入流程名称");
            if (flowName&&flowName.length>0) {
                $.ajax({
                    url: '@Url.Action("Save","Default")',
                    data: { NAME: flowName, XML: exportObj.XML, IMAGE: exportObj.IMAGE, WFID: '@ViewBag.WfID' },
                    type: 'POST',
                    success: function () {
                        alert("操作成功");
                    }
                });
            } else {
                alert("请输入流程名称");
            }
        }
        $(function () {
            window.SMF.bind('drawing');
            var WFID = '@ViewBag.WfID';
            if (WFID !== '0') {
                $.ajax({
                    url: '@Url.Action("GetResult", "Default")',
                    type: 'post',
                    dataType: 'json',
                    data: { WFID: WFID },
                    success: function (serverData) {
                        //SMF.revert(serverData,false,1);
                        SMF.revert(serverData.IMAGE);
                    }
                })
            } else {
                SMF.create('start');
                SMF.create('end');
            }
        });
    </script>
</head>
<body>
    <div class="tools">
        <ul class="tools-menu">
            <li>
                <a href="#" onclick="saveflow()">保存</a>
            </li>
            <li>
                <a href="#" onclick="SMF.select()">选择</a>
            </li>
            <li>
                <a href="#" onclick="SMF.connect()">连接</a>
            </li>
            <li>
                <a href="#" onclick="SMF.create('node')">节点</a>
            </li>
            <li>
                <a href="#" onclick="SMF.create('decision')">决策</a>
            </li>
        </ul>
    </div>
    <div class="container">
        <div class="container-draw" id="drawing"></div>
    </div>
</body>
</html>

Smartflow.Web/Views/Shared/List.cshtml
@model System.Collections.Generic.IEnumerable<Smartflow.Web.Code.WorkflowXml>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Smartflow 工作流程列表</title>
    <style type="text/css">
        .panel {
            width: 98%;
            margin: 0 auto;
        }

        .table {
            width: 100%;
            min-width: 800px;
        }

            .table td {
                border-bottom: solid 1px #eee;
                line-height: 28px;
            }

            .table th {
                border-bottom: solid 1px #eee;
                line-height: 35px;
            }

        .btn {
            padding: 5px 10px;
            border: solid 1px #EFC10C;
            margin-bottom: 3px;
        }
    </style>
    <script src="~/Content/jquery-1.6.4.min.js"></script>
    <script type="text/javascript">
        function openWin(url) {
            var iTop = (window.screen.availHeight - 30 - 560) / 2;
            var iLeft = (window.screen.availWidth - 10 - 960) / 2;
            window.open(url, 'newwindow', "height=560, width=960, top=" + iTop + " left=" + iLeft + ", toolbar=no, menubar=no, scrollbars=no, resizable=no,location=no, status=no");
        }

        function delWf(id) {

            if (window.confirm('删除？')) {

                $.ajax({
                    url: '@Url.Action("Delete", "Default")',
                    type: 'post',
                    data: { WFID: id },
                    success: function () {
                        document.location.href = '@Url.Action("List","Default")';
                    }
                });

            }
        }

    </script>
</head>
<body>
    <div class="panel panel-default">
        <div style="text-align:right;">
            <!-- Default panel contents -->
            <input type="button" value="增加" class="btn" onclick="openWin('@Url.Action("Index","Default")')" />
            <!-- Table -->
        </div>
        <table class="table  table-hover">
            <thead>
                <tr>
                    <th style="width:50px;">序号</th>
                    <th>名称</th>
                    <th style="width:120px;">操作</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                }
                @foreach (Smartflow.Web.Code.WorkflowXml wf in Model)
                {
                    <tr>
                        <td style="width:50px;text-align:center;">@(counter++)</td>
                        <td>@wf.NAME</td>
                        <td style="width:120px;text-align:center;">
                            <a href="javascript:openWin('@Url.Action("Index", "Default" , new { id=wf.WFID })')">修改</a>
                            <a href="javascript:delWf('@wf.WFID')">删除</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Smartflow.Web/Views/Shared/flowImage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Smartflow 业务流程图</title>
    <link href="~/Content/smartflow.css" rel="stylesheet" />
    <script src="~/Content/jquery-1.6.4.min.js"></script>
    <script src="~/Content/svg.js"></script>
    <script src="~/Content/smartflow.js"></script>
    <script type="text/javascript">
        $(function () {
            var draw = window.SMF.bind('drawing');
            var WFID = '@ViewBag.WfID';
            if (WFID !== '0') {
                $.ajax({
                    url: '@Url.Action("GetResult", "UserCtl")',
                    type: 'post',
                    dataType: 'json',
                    data: { instanceID: WFID },
                    success: function (serverData) {
                        SMF.revert(serverData.Image, true, serverData.Current.ID);
                    }
                })
            } else {
                draw.create('start');
                draw.create('end');
            }
        });
    </script>
</head>
<body>
    <div class="container">
        <div class="container-draw" id="drawing"></div>
    </div>
</body>
</html>

Smartflow.Web/Views/WorkflowDesign/List.cshtml
@model System.Collections.Generic.IEnumerable<Smartflow.WorkflowXml>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Smartflow 工作流程列表</title>
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Content/jquery.min.js"></script>
    <script src="~/Content/common.js"></script>
    <script type="text/javascript">
        function delWf(id) {
            if (window.confirm('删除？')) {
                $.ajax({
                    url: '@Url.Action("Delete", "WorkflowDesign")',
                    type: 'post',
                    data: { WFID: id },
                    success: function () {
                        document.location.href = '@Url.Action("List", "WorkflowDesign")';
                    }
                });
            }
        }
    </script>
</head>
<body>
    <div class="panel panel-default">
        <div style="text-align:right;">
            <!-- Default panel contents -->
            <input type="button" value="增加" class="btn" onclick="openWin('@Url.Action("Index", "WorkflowDesign")',960,560)" />
            <!-- Table -->
        </div>
        <table class="table table-list">
            <thead>
                <tr>
                    <th style="width:50px;">序号</th>
                    <th>名称</th>
                    <th style="width:120px;">操作</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                }
                @foreach (Smartflow.WorkflowXml wf in Model)
                {
                    <tr>
                        <td style="width:50px;text-align:center;">@(counter++)</td>
                        <td>@wf.NAME</td>
                        <td style="width:120px;text-align:center;">
                            <a href="javascript:openWin('@Url.Action("Index", "WorkflowDesign", new { id = wf.WFID })',960,560)">修改</a>
                            <a href="javascript:delWf('@wf.WFID')">删除</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>