example/Smartflow.Web.Mvc/Controllers/FileApplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Smartflow.BussinessService.Models;
using Smartflow.BussinessService.WorkflowService;
using Smartflow.BussinessService.Services;
using Smartflow.Web.Mvc.Code;

namespace Smartflow.Web.Controllers
{
    public class FileApplyController : Controller
    {
        private BaseWorkflowService bwfs = BaseWorkflowService.Instance;
        private ApplyService fileApplyService = new ApplyService();

        public ActionResult Save(Apply model)
        {
            model.STATUS = 0;
            fileApplyService.Persistent(model);
            return RedirectToAction("FileApplyList");
        }

        public ActionResult Submit(Apply model)
        {
            model.INSTANCEID = bwfs.Start(model.STRUCTUREID);
            model.STATUS = 1;
            fileApplyService.Persistent(model);
            return RedirectToAction("FileApplyList");
        }

        public ActionResult FileApplyList()
        {
            return View(fileApplyService.Query());
        }

        public void Delete(long id)
        {
            fileApplyService.Delete(id);
        }

        public ActionResult FileApply(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                GenerateSecretViewData(string.Empty);
                GenerateWFViewData(string.Empty);
                return View();
            }
            else
            {
                Apply mdl = fileApplyService.GetInstance(long.Parse(id));
                GenerateSecretViewData(mdl.SECRETGRADE);
                GenerateWFViewData(mdl.STRUCTUREID);

                if (mdl.STATUS == 1)
                {
                    var executeNode = bwfs.GetCurrentPrevNode(mdl.INSTANCEID);
                    var current = bwfs.GetCurrent(mdl.INSTANCEID);

                    ViewBag.ButtonName = current.APPELLATION;
                    ViewBag.PreviousButtonName = executeNode == null ? String.Empty : executeNode.APPELLATION;
                    ViewBag.UndoCheck = CommonMethods.CheckUndoButton(mdl.INSTANCEID);
                    ViewBag.UndoAuth = executeNode == null ? true : CommonMethods.CheckUndoAuth(mdl.INSTANCEID);
                    ViewBag.JumpAuth = current.APPELLATION == "开始" ? true : CommonMethods.CheckAuth(current.NID, mdl.INSTANCEID);
                    ViewBag.UserList= new UserService().GetPendingUserList(current.NID, mdl.INSTANCEID);
                }
                return View(mdl);
            }
        }

        public void GenerateWFViewData(string WFID)
        {
            List<WorkflowStructure> workflowXmlList = WorkflowServiceProvider
                .OfType<IWorkflowDesignService>()
                .GetWorkflowStructureList();
            
            
            List<SelectListItem> fileList = new List<SelectListItem>();
            foreach (WorkflowStructure item in workflowXmlList)
            {
                fileList.Add(new SelectListItem { Text = item.APPELLATION, Value = item.IDENTIFICATION, Selected = (item.IDENTIFICATION == WFID) });
            }
            ViewData["WFiles"] = fileList;
        }

        public void GenerateSecretViewData(string secretGrade)
        {
            List<string> secrets = new List<string>() { 
              "非密",
              "秘密",
              "机密",
              "绝密"
            };
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (string secret in secrets)
            {
                list.Add(new SelectListItem { Text = secret, Value = secret, Selected = (secret == secretGrade) });
            }
            ViewData["SECRET"] = list;
        }
    }
}

example/Smartflow.Web.Mvc/Controllers/UserControlController.cs
/*
 License: https://github.com/chengderen/Smartflow/blob/master/LICENSE 
 Home page: https://github.com/chengderen/Smartflow
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Dynamic;
using Smartflow;
using Smartflow.Elements;


using Smartflow.BussinessService.WorkflowService;
using Smartflow.BussinessService.Models;
using Smartflow.BussinessService.Services;
using Smartflow.Web.Mvc.Code;

namespace Smartflow.Web.Controllers
{
    public class UserControlController : Controller
    {
        private RecordService workflowRecordService = new RecordService();
        private BaseWorkflowService bwkf = BaseWorkflowService.Instance;

        public PartialViewResult Record(string instanceID)
        {
            ViewBag.InstanceID = instanceID;
            return PartialView(workflowRecordService.Query(instanceID));
        }

        /// <summary>
        /// 依据跳转跳线获取下节点审批用户列表
        /// </summary>
        /// <param name="instanceID">流程实例</param>
        /// <param name="transitionID">跳转路线ID</param>
        /// <returns>用户列表</returns>
        public JsonResult GetUsers(string instanceID, string transitionID)
        {
            WorkflowInstance instance = WorkflowInstance.GetInstance(instanceID);
            List<Group> groupList = instance.Current.GetNextGroup(transitionID);
            List<string> gList = new List<string>();
            foreach (Group g in groupList)
            {
                gList.Add(g.IDENTIFICATION.ToString());
            }
            List<User> userList = new UserService().GetUserList(string.Join(",", gList));

            return Json(userList);
        }

        /// <summary>
        /// 工作流组件
        /// </summary>
        /// <param name="instanceID">流程实例ID</param>
        /// <returns></returns>
        public ActionResult WorkflowCheck(string instanceID, string bussinessID)
        {
            ViewBag.InstanceID = instanceID;
            ViewBag.bussinessID = bussinessID;
            WorkflowInstance instance = WorkflowInstance.GetInstance(instanceID);
            ViewBag.CheckResult = CommonMethods.CheckUndoButton(instanceID);
            return View(instance.Current.GetTransitions());
        }

        /// <summary>
        /// 撤销操作
        /// </summary>
        /// <param name="instanceID">流程实例ID</param>
        /// <returns></returns>
        public JsonResult UndoCheck(string instanceID, string bussinessID)
        {
            User userInfo = System.Web.HttpContext.Current.Session["user"] as User;
            bwkf.UndoSubmit(instanceID, userInfo.IDENTIFICATION, userInfo.EMPLOYEENAME, bussinessID);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 流程跳转处理接口(请不要直接定义匿名类传递)
        /// </summary>
        /// <param name="instanceID">流程实例ID</param>
        /// <param name="transitionID">跳转路线ID</param>
        /// <param name="message">审批消息</param>
        /// <param name="action">审批动作（原路退回、跳转）</param>
        /// <returns>是否成功</returns>
        public JsonResult Jump(string instanceID, string transitionID, string bussinessID, string message, string action)
        {
            User userInfo = System.Web.HttpContext.Current.Session["user"] as User;
            dynamic data = new ExpandoObject();
            data.Message = message;
            data.bussinessID = bussinessID;
            data.UserInfo = userInfo;
            switch (action.ToLower())
            {
                case "rollback":
                    bwkf.Rollback(instanceID, userInfo.IDENTIFICATION, userInfo.EMPLOYEENAME, data);
                    break;
                default:
                    bwkf.Jump(instanceID, transitionID, userInfo.IDENTIFICATION, userInfo.EMPLOYEENAME, data);
                    break;
            }
            return Json(true);
        }
    }
}

example/Smartflow.Web.Mvc/Views/FileApply/FileApply.cshtml
@model Smartflow.BussinessService.Models.Apply
@using Smartflow.BussinessService.Models
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>业务流程</title>
    <link href="~/Content/main.css" rel="stylesheet" />
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <script src="~/Content/common.js"></script>
    <script src="~/Content/jquery.min.js"></script>
    <style type="text/css">
        .layui-input {
            height: 30px;
            min-height: 30px;
            width: 100%;
            border: none;
        }

        .layui-select {
            width: 100%;
            border: none;
        }

        .layui-textarea {
            width: 100%;
            border: none;
            resize: none;
        }

        .layui-btn {
            border-radius: initial;
        }

        input[disabled] {
            border: 1px solid #e6e6e6;
            background-color: #FBFBFB;
            color: #C9C9C9;
            cursor: not-allowed;
        }
    </style>
    <script type="text/javascript">
        function save(url) {
            $("#formFileApply").attr("action", url);
            return true;
        }
        $(function () {
            loadBtnAuth();
        });

        function loadBtnAuth() {
            var status = $("#STATUS").val();
            switch (status) {
                case "0":
                    $("#btnSubmit,#btnSave").show();
                    $("#btnAudit,#btnUnAudit").hide();
                    break;
                case "1":
                    $("#btnAudit").show();
                    $("#btnSubmit,#btnSave").hide();
                    $("#btnUnAudit")['@ViewBag.UndoCheck' == 'False' ? 'show' : 'hide']();
                    break;
                case "8":
                    $("#btnAudit").hide();
                    $("#btnSubmit,#btnSave,#btnUnAudit").hide();
                    break;
                default:
                    $("#btnAudit,#btnUnAudit").hide();
                    break;
            }
        }


        function auditApply() {
            var instanceID = document.getElementById("INSTANCEID").value;
            var bussinessID = document.getElementById("IDENTIFICATION").value;
            openWin('@Url.Action("WorkflowCheck", "UserControl")' + "?instanceID=" + instanceID + "&bussinessID=" + bussinessID, 600, 300);
        }

        function undoCheck() {
            var instanceID = document.getElementById("INSTANCEID").value;
            var bussinessID = document.getElementById("IDENTIFICATION").value;
            $.ajax({
                url: '@Url.Action("UndoCheck", "UserControl")' + "?instanceID=" + instanceID + "&bussinessID=" + bussinessID,
                dataType: 'json',
                type: 'get',
                success: function () {
                    doRefresh();
                }
            });
        }

        function doRefresh() {
            var url = window.location.href;
            if (url.indexOf("?") > -1) {
                url = url.substring(0, url.lastIndexOf("?"));
            }
            window.location.href = url + '?t=' + new Date().getTime();
        }
    </script>
</head>
<body>
    <div class="layui-container">
        <form id="formFileApply">
            @Html.HiddenFor(m => m.IDENTIFICATION)
            @Html.HiddenFor(m => m.INSTANCEID)
            @Html.HiddenFor(m => m.STATUS)
            <table class="layui-table">
                <tr>
                    <td style="width:100px;text-align:right;">文件名称</td>
                    <td>@Html.TextBoxFor(m => m.FNAME, new { @class = "layui-input" })</td>
                    <td style="width:100px;text-align:right;">申请密级</td>
                    <td>@Html.DropDownListFor(m => m.SECRETGRADE, (ViewData["SECRET"] as IEnumerable<SelectListItem>), new { @class = "layui-select" })</td>
                </tr>
                <tr>
                    <td style="width:100px;text-align:right;">审批流程</td>
                    <td colspan="3">
                        @Html.DropDownListFor(m => m.STRUCTUREID, (ViewData["WFiles"] as IEnumerable<SelectListItem>), new { @class = "layui-select" })
                    </td>
                </tr>
                <tr>
                    <td style="width:100px;text-align:right;">备注</td>
                    <td colspan="3">
                        @Html.TextAreaFor(m => m.DESCRIPTION, new { @class = "layui-textarea" })
                    </td>
                </tr>
                <tr>
                    <td colspan="4" style="text-align:center;">
                        <input type="button" id="btnUnAudit" class="layui-btn" @(ViewBag.UndoAuth == true ? "" : "disabled") value="@("撤销" + ViewBag.PreviousButtonName)" onclick="undoCheck()" />
                        <input type="button" id="btnAudit" class="layui-btn" @(ViewBag.JumpAuth == true ? "" : "disabled") value="@ViewBag.ButtonName" onclick="auditApply()" />
                        <input type="submit" id="btnSubmit" value="提交" class="layui-btn " onclick="return save('@Url.Action("Submit", "FileApply")')" />
                        <input type="submit" id="btnSave" value="保存" class="layui-btn layui-btn-normal" onclick="return save('@Url.Action("Save", "FileApply")')" />
                        <input type="button" id="btnBack" value="返回" class="layui-btn layui-btn-warm" onclick="window.location.href = '@Url.Action("FileApplyList", "FileApply")'" />
                    </td>
                </tr>
                <tr style="display:@(ViewBag.UserList != null ? "table-row" : "none")">
                    <td colspan="4">
                        1、谁审谁撤销；
                        2、原路退回，谁审退给谁；
                        3、本节点待审批账户：
                        @{
                            if (ViewBag.UserList != null)
                            {
                                foreach (User userInfo in ViewBag.UserList)
                                {
                                    <span style="color:red;">
                                        @(string.Format("{0}({1})", userInfo.USERNAME, userInfo.EMPLOYEENAME))
                                    </span>
                                }
                            }
                        }
                    </td>

                </tr>
            </table>
        </form>
        @{
            if (Model != null)
            {
                Html.RenderAction("Record", "UserControl", new { instanceID = Model.INSTANCEID });
            }
        }
    </div>
</body>
</html>

example/Smartflow.Web.Mvc/Views/FileApply/FileApplyList.cshtml
@model System.Collections.Generic.IEnumerable<Smartflow.BussinessService.Models.Apply>
@using Smartflow.BussinessService.Models
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>业务流程</title>
    <link href="~/Content/layui/css/layui.css" rel="stylesheet" />
    <style type="text/css">
         .layui-btn {border-radius: initial;}
    </style>
    <script src="~/Content/jquery.min.js"></script>
    <script type="text/javascript">
        function delApply(id) {
            if (window.confirm('删除？')) {
                $.ajax({
                    url: '@Url.Action("Delete", "FileApply")',
                    type: 'post',
                    data: { id: id },
                    success: function () {
                        document.location.href = '@Url.Action("FileApplyList", "FileApply")';
                    }
                });
            }
        }
    </script>
</head>
<body>
    <br />
    <div class="layui-container">
        <div class="layui-btn-group">
            <input type="button" value="增加" class="layui-btn layui-btn-sm" onclick="document.location.href='@Url.Action("FileApply", "FileApply")'" />
        </div>
        <table class="layui-table">
            <thead>
                <tr>
                    <th style="width:160px;text-align:left;">文件名称</th>
                    <th style="width:70px;text-align:center;">表单状态</th>
                    <th style="width:70px;text-align:center;">申请密级</th>
                    <th>备注</th>
                    <th style="width:120px;text-align:center;">操作</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Apply mdl in Model)
                {
                    <tr>
                        <td style="width:160px;text-align:left;">@mdl.FNAME</td>
                        <td style="width:70px;text-align:center;">@mdl.STATUSNAME</td>
                        <td style="width:70px;text-align:center;">@mdl.SECRETGRADE</td>
                        <td style="text-align:left;">@mdl.DESCRIPTION</td>
                        <td style="width:180px;text-align:center;">
                            <a class="layui-btn layui-btn-primary layui-btn-xs" href="@Url.Action("FileApply", "FileApply", new { id=mdl.IDENTIFICATION })" target="_self">查看</a>
                            <a class="layui-btn layui-btn-danger layui-btn-xs" href="javascript:delApply('@mdl.IDENTIFICATION')">删除</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>